name: Varbase AI Default
description: A recipe to configure default AI modules, settings, and permissions in Varbase, enabling OpenAI integrations for alt-text generation, CKEditor enhancements, and various AI-powered features.
type: Varbase AI
install:
  - key
  - ai
  - ai_provider_openai
  - ai_image_alt_text
  - ai_automators
  - ai_ckeditor
input:
  ai_api_key:
    data_type: string
    description: The OpenAI API key.
    prompt:
      method: ask
      arguments:
        question: 'Enter an OpenAI API key:'
    default:
      source: value
      value: 'sk-change-this'
config:
  import:
    ai: '*'
    ai_provider_openai: '*'
    ai_image_alt_text: '*'
    ai_automators: '*'
    ai_ckeditor: '*'
  actions:
    key.key.open_ai_key:
      createIfNotExists:
        langcode: en
        status: true
        dependencies: {  }
        id: open_ai_key
        label: 'Open AI Key'
        description: ''
        key_type: authentication
        key_type_settings: {  }
        key_provider: config
        key_provider_settings:
          key_value: ${ai_api_key}
        key_input: text_field
        key_input_settings: {  }
    ai_provider_openai.settings:
      simpleConfigUpdate:
        api_key: open_ai_key
        moderation: true
        host: ''
    ai.settings:
      simpleConfigUpdate:
        default_providers:
          chat:
            provider_id: openai
            model_id: gpt-4o
          chat_with_complex_json:
            provider_id: openai
            model_id: gpt-4o
          chat_with_image_vision:
            provider_id: openai
            model_id: gpt-4o
          embeddings:
            provider_id: openai
            model_id: text-embedding-3-small
          moderation:
            provider_id: openai
            model_id: omni-moderation-latest
          speech_to_text:
            provider_id: openai
            model_id: whisper-1
          text_to_image:
            provider_id: openai
            model_id: dall-e-3
          text_to_speech:
            provider_id: openai
            model_id: tts-1-hd
    editor.editor.basic_html:
      addButtonPluginIntoActiveToolbar:
        button_name: aickeditor
        button_index: 0
        plugin_name: ai_ckeditor_ai
        plugin_settings:
          dialog:
            autoresize: 'min-width: 600px'
            height: '750'
            width: '900'
            dialog_class: ai-ckeditor-modal
          plugins:
            ai_automators_ckeditor:
              workflows: {  }
              enabled: true
            ai_ckeditor_completion:
              provider: openai__gpt-4o
              enabled: true
            ai_ckeditor_help:
              enabled: false
            ai_ckeditor_reformat_html:
              provider: openai__gpt-4o
              enabled: true
            ai_ckeditor_spellfix:
              provider: openai__gpt-4o
              enabled: true
            ai_ckeditor_summarize:
              provider: openai__gpt-4o
              enabled: true
            ai_ckeditor_tone:
              autocreate: false
              provider: openai__gpt-4o
              tone_vocabulary: ''
              use_description: 0
              enabled: true
            ai_ckeditor_translate:
              enabled: false
    editor.editor.full_html:
      addButtonPluginIntoActiveToolbar:
        button_name: aickeditor
        button_index: 0
        plugin_name: ai_ckeditor_ai
        plugin_settings:
          dialog:
            autoresize: 'min-width: 600px'
            height: '750'
            width: '900'
            dialog_class: ai-ckeditor-modal
          plugins:
            ai_automators_ckeditor:
              workflows: {  }
              enabled: true
            ai_ckeditor_completion:
              provider: openai__gpt-4o
              enabled: true
            ai_ckeditor_help:
              enabled: false
            ai_ckeditor_reformat_html:
              provider: openai__gpt-4o
              enabled: true
            ai_ckeditor_spellfix:
              provider: openai__gpt-4o
              enabled: true
            ai_ckeditor_summarize:
              provider: openai__gpt-4o
              enabled: true
            ai_ckeditor_tone:
              autocreate: false
              provider: openai__gpt-4o
              tone_vocabulary: ''
              use_description: 0
              enabled: true
            ai_ckeditor_translate:
              enabled: false
    user.role.site_admin:
      grantPermissions:
        - 'generate ai alt tags'
        - 'use ai ckeditor'
    user.role.seo_admin:
      grantPermissions:
        - 'generate ai alt tags'
        - 'use ai ckeditor'
    user.role.content_admin:
      grantPermissions:
        - 'generate ai alt tags'
        - 'use ai ckeditor'
    user.role.editor:
      grantPermissions:
        - 'generate ai alt tags'
        - 'use ai ckeditor'
