name: Varbase AI Taxonomy Tagging
description: Provides a recipe to automatically tag selected referenced taxonomy terms based on the content entity's body field.
type: Varbase AI
install:
  - node
  - taxonomy
  - ai
  - ai_automators
input:
  content_type:
    data_type: string
    description: Content Type
    prompt:
      method: ask
      arguments:
        question: 'Content Type:'
    default:
      source: value
      value: 'varbase_blog'
  field_name:
    data_type: string
    description: Filed name
    prompt:
      method: ask
      arguments:
        question: 'Filed name:'
    default:
      source: value
      value: 'field_tags'
config:
  strict: false
  actions:
    field.storage.node.ai_automator_status:
      createIfNotExists:
        langcode: en
        status: true
        id: node.ai_automator_status
        field_name: ai_automator_status
        entity_type: node
        type: list_string
    field.field.node.${content_type}.ai_automator_status:
      createIfNotExists:
        status: true
        id: node.${content_type}.ai_automator_status
        field_name: ai_automator_status
        entity_type: node
        bundle: ${content_type}
        label: 'AI Automator Status'
        description: ''
        required: true
        translatable: true
        default_value:
          - pending
        default_value_callback: ''
        settings: {  }
        field_type: list_string
    ai_automators.ai_automator.node.${content_type}.${field_name}.default:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          config:
            - field.field.node.${content_type}.${field_name}
        id: node.${content_type}.${field_name}.default
        label: 'Tags Default'
        rule: llm_taxonomy
        input_mode: base
        weight: 100
        worker_type: direct
        entity_type: node
        bundle: ${content_type}
        field_name: ${field_name}
        edit_mode: false
        base_field: body
        prompt: "Based on the context text choose up to {{ max_amount }} keyword tags from the tag context that fits the text.\r\n\r\nTag options:\r\n{{ value_options_comma }}\r\n\r\nContext:\r\n{{ context }}"
        token: ""
        plugin_config:
          automator_enabled: 1
          automator_rule: llm_taxonomy
          automator_mode: base
          automator_base_field: body
          automator_prompt: "Based on the context text choose up to {{ max_amount }} keyword tags from the tag context that fits the text.\r\n\r\nTag options:\r\n{{ value_options_comma }}\r\n\r\nContext:\r\n{{ context }}"
          automator_token: ""
          automator_edit_mode: 0
          automator_label: 'Tags Default'
          automator_weight: '100'
          automator_worker_type: direct
          automator_ai_provider: default_json
          automator_clean_up: ''
          automator_search_similar_tags: 0
